### ISSUE TITLE
does not work on php 5.3 here is a proposed solution 

### ISSUE THREAD

**Issue by sidd-kishan** [jakezatecky/array_group_by#1]
function fn_array_group_by( array $array, $key )
    {
        if ( ! is_string( $key ) && ! is_int( $key ) && ! is_float( $key ) && ! is_callable( $key ) ) {
            trigger_error( 'fn_array_group_by(): The key should be a string, an integer, or a callback', E_USER_ERROR );
            return null;
        }
        $func = ( is_callable( $key ) ? $key : null );
        $_key = $key;
        // Load the new array, splitting by the target key
        $grouped = array();
        foreach ( $array as $value ) {
            if ( is_callable( $func ) ) {
                $key = call_user_func( $func, $value );
            } elseif ( is_object( $value ) && isset( $value->{ $_key } ) ) {
                $key = $value->{ $_key };
            } elseif ( isset( $value[ $_key ] ) ) {
                $key = $value[ $_key ];
            } else {
                continue;
            }
            $grouped[ $key ][] = $value;
        }
        // Recursively build a nested grouping if more parameters are supplied
        // Each grouped array value is grouped according to the next sequential key
        if ( func_num_args() > 2 ) {
            $args = func_get_args();
            foreach ( $grouped as $key => $value ) {
                $params = array_merge( array( $value), array_slice( $args, 2, func_num_args() ) );
                $grouped[ $key ] = call_user_func_array( 'fn_array_group_by', $params );
            }
        }
        return $grouped;
    }
/*
it is beacuse of the $grouped = [];
and 
array_merge( [$value], array_slice( $args, 2, func_num_args() ) );
which is cahnged to 
array_merge( array( $value), array_slice( $args, 2, func_num_args() ) );
*/

**Comment by sidd-kishan** [comment]
test code is also need to be changed for php 5.3 such as the following:-

```
$records = array(
array(
    'state'  => 'IN',
    'city'   => 'Indianapolis',
    'object' => 'School bus',
),
array(
    'state'  => 'IN',
    'city'   => 'Indianapolis',
    'object' => 'Manhole',
),
array(
    'state'  => 'IN',
    'city'   => 'Plainfield',
    'object' => 'Basketball',
),
array(
    'state'  => 'CA',
    'city'   => 'San Diego',
    'object' => 'Light bulb',
),
array(
    'state'  => 'CA',
    'city'   => 'Mountain View',
    'object' => 'Space pen',
)
```

);
print_r(fn_array_group_by($records,'state','city'));

**Comment by jakezatecky** [comment]
Hey there --

PHP 5.3 was end of life'd in [2014](https://secure.php.net/eol.php) and I generally do not want to support versions that even the core developers do not want to support. I also think the 5.4 array syntax is much more elegant.

A previous version of the library did support PHP 5.3, but it was [explicitly removed](https://github.com/jakezatecky/array_group_by/commit/565b375ea7346ff49097b34b0f30e5c069434c7e). You are free to use v0.7.3 if you want support for 5.3:

https://github.com/jakezatecky/array_group_by/tree/0.7.3

**Comment by sidd-kishan** [comment]
Thanks for the sugestion.
